require("plugins.plugin_setup")
require("core.options")
require("core.keymaps")

-- 插件
require("plugins.lualine")
require("plugins.nvim_tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.golang")
-- require("plugins.flash")
require("plugins.lspsaga")
require("plugins.indent")

require("plugins.which-key")
-- require("plugins.trouble")
require("plugins.dashboard")
require("plugins.conform")
require("plugins.lsp_kind")
require("plugins.debugging")
require("plugins.toggleterm")
-- require("plugins.lsp_signature")
-- require("neo-tree")
